spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/redis_cache_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60s
      cache-null-values: false

server:
  port: 8080

logging:
  level:
    org.springframework.cache: INFO

