spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/redis_cache_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always

server:
  port: 8080

